# Generated by Django 5.1.3 on 2024-12-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiarticle',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
