# Generated by Django 5.1.3 on 2024-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0003_alter_wikiarticle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
